### ISSUE TITLE
Ошибка выполнения script.js

### ISSUE THREAD

**Issue by JohnyDeath** [ret-Phoenix/v8CfgAddsAhk#1]
Windows 2012 R2
Библиотеки зарегистрированы.
Запустил ..\v8CfgAddsAhk\v8CfgAdds64.ahk (кстати, наверное стоит подправить документацию в этом плане)
Далее добавил ассоциации для js файлов на программу c:\WINDOWS\SysWOW64\cscript.exe 

При выполнении в конфигураторе ctrl+1, alt+f... вываливает:
![image](https://cloud.githubusercontent.com/assets/5936030/15450842/b743fb00-1fb1-11e6-9e9b-e2d7bde4f480.png)

**Comment by ret-Phoenix** [comment]
RunWait, %A_WinDir%\SysWOW64\wscript scripts.js %module% search
не тот exe файл приспользуется (c:\WINDOWS\SysWOW64\cscript.exe) . Лучше убрать ассоциацию и оставить как сделано мной (wscript)

**Comment by ret-Phoenix** [comment]
Разобрался. Необходимо создать папку tmp  там же, где лежат скрипты.
Пересмотрю этот момент, постараюсь к системным темпам обращаться.

**Comment by JohnyDeath** [comment]
Да, после создания папки tmp в каталоге скриптов - все заработало.
Но я запуская сразу из клона твоего репозитория, поэтому, конечно, лучше обращаться к системному tmp, чтобы не создавать такой каталог при каждом обновлении репозитория.
Или же в крайнем случае создать в базовом репо tmp )
