### ISSUE TITLE
Переписать ++/+=/--/-=

### ISSUE THREAD

**Issue by ret-Phoenix** [ret-Phoenix/v8CfgAddsAhk#51]
Работает не стабильно, лучше сделать на oscript

**Comment by 7OH** [comment]
скачал сегодня мастер ветку - у меня а+= выдало а = а - ;
и больше вообще не реагирует

**Comment by ret-Phoenix** [comment]
Надо смотреть ветку DEV, там все работает. слово (комбинация +/-) Enter
