### ISSUE TITLE
В окне списка методов отображается "Соответствие", если ни один из методов не подходит под фильтр (при выборе через gui)

### ISSUE THREAD

**Issue by demidych** [ret-Phoenix/v8CfgAddsAhk#64]
Если в окне списка методов указать такой фильтр, под который не подходит не один из методов, то в списке отобразится слово "Соответствие" вместо пустого списка.

**Comment by ret-Phoenix** [comment]
Исправлено в ветке DEV. теперь если нет подходящих по условию - показывает все.
